# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: ${NAMESPACE}
spec:                               
  externalTrafficPolicy: Local      # externalTraffic Local
  type: NodePort
  selector:                         
    app: ${APP_NAME}                
  ports:
  - name: http
    protocol: TCP
    port: 10082                                                                                                                 
    targetPort: 10082                                                  
                                    
---

# DEPOLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:                           
  name: ${APP_NAME}                  
  namespace: ${NAMESPACE}
spec:
  replicas: 3
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate            
    rollingUpdate:                  
      maxSurge: 2
      maxUnavailable: 0
  selector:                         
    matchLabels:
      app: ${APP_NAME}
  template:                          
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: ncloud.com/nks-nodepool
                  operator: In
                  values:
                    - ${NODE_NAME}
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE}
        imagePullPolicy: Always          
        ports:
        - name: http
          containerPort: 10082                                       
        resources:
          requests:                                                     
            memory: "1Gi"
            cpu: "500m"
          limits:                                                     
            memory: "1Gi"
            cpu: "1000m"
        startupProbe:         ## *성공 할 때까지 트래픽을 받지 않음(다른 Probe들도 실행하지 않음)
          httpGet:
            path: /
            port: 10082
            #scheme: HTTPS - Spring Boot App내부에서는 http를 사용함
          failureThreshold: 30    # probe가 명령 수행 후 실패라고 판단하기 위한 최소 횟수, probe가 횟수 이상 실패하면 컨테이너 중지 후 재시작(default:3)
        lifecycle:                
          preStop:
            exec:
              command: ["sh", "-c", "sleep 20"]             
      imagePullSecrets:
      - name: regcred-ns-auth
---
      
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa             
  namespace: ${NAMESPACE}
spec:                                  
  maxReplicas: 6
  minReplicas: 3
  scaleTargetRef:                      
    apiVersion: apps/v1          
    kind: Deployment                  
    name: ${APP_NAME}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 60      

            
