# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
spec:                               
  type: NodePort
  selector:                         
    app: ${APP_NAME}                
  ports:
  - name: http
    protocol: TCP
    port: 10081                                                                                                   
    targetPort: 8081                                    
                                    
---

# DEPOLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:                           
  name: ${APP_NAME}                  
spec:
  replicas: 1                       
  revisionHistoryLimit: 2           
  strategy:
    type: RollingUpdate            
    rollingUpdate:                  
      maxSurge: 1        
      maxUnavailable: 0
  selector:                         
    matchLabels:
      app: ${APP_NAME}
  template:                          
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE}
        imagePullPolicy: Always          
        ports:
        - name: http
          containerPort: 8081                         
        resources:
          requests:                                                     
            memory: "512Mi"                                                
            cpu: "500m"
          limits:                                                     
            memory: "1Gi"                                                
            cpu: "1000m"
        livenessProbe:              
          exec:
            command: ["sh", "-c", "cd /"]              
          initialDelaySeconds: 30
          periodSeconds: 30                      
        readinessProbe:
          exec:
            command: ["sh", "-c", "cd /"]  
          initialDelaySeconds: 30
          periodSeconds: 15       
        lifecycle:                
          preStop:
            exec:
              command: ["sh", "-c", "sleep 20"]             
      imagePullSecrets:
      - name: regcred-ns-auth

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa             
spec:                                  
  maxReplicas: 5
  minReplicas: 1                 
  scaleTargetRef:                      
    apiVersion: apps/v1          
    kind: Deployment                  
    name: ${APP_NAME}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70

            
