# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: ${NAMESPACE}
spec:                               
  type: NodePort
  selector:                         
    app: ${APP_NAME}
  ports:
  - name: http
    protocol: TCP
    port: 58090
    targetPort: 58090
                                    
---
# DEPOLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:                           
  name: ${APP_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1                                     
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate            
    rollingUpdate:                  
      maxSurge: 1                      
      maxUnavailable: 0              
  selector:                         
    matchLabels:
      app: ${APP_NAME}
  template:                          
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: ncloud.com/nks-nodepool
                  operator: In
                  values:
                    - ${NODE_NAME}
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE}
        imagePullPolicy: Always          
        ports:
        - name: http
          containerPort: 58090
        resources:
          requests:                                                     
            memory: "256Mi"                                                
            cpu: "250m"
          limits:                                                     
            memory: "512Mi"                                                
            cpu: "500m"
        livenessProbe:              
          exec:
            command: ["sh", "-c", "cd /"]              
          initialDelaySeconds: 30
          periodSeconds: 30                      
        readinessProbe:
          exec:
            command: ["sh", "-c", "cd /"]  
          initialDelaySeconds: 30
          periodSeconds: 15       
        lifecycle:                
          preStop:
            exec:
              command: ["sh", "-c", "sleep 20"]             
      imagePullSecrets:
      - name: regcred-${NAMESPACE}

---
#HPA      
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ${APP_NAME}-hpa
  namespace: ${NAMESPACE}
spec:                                  
  maxReplicas: 3                      
  minReplicas: 1                 
  scaleTargetRef:                      
    apiVersion: apps/v1          
    kind: Deployment                  
    name: ${APP_NAME}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70